config/urls.py
from django.contrib import admin as djangoadmin
from django.contrib.auth import views as auth_views
from django.urls import include, path
from django.views.static import serve

from app.obj import forms as siteforms
from app.pages import feeds as sitefeeds
from .settings.base import STATIC_ROOT

urlpatterns = [
    path('', include('app.views.home', namespace='home')),
    path('admin/', include('app.views.admin.urls', namespace='catmin')),
    path('history/', include('app.views.history.urls', namespace='history')),
    path('highlights/', include('app.views.highlights.urls', namespace='highlights')),
    path('casualties/', include('app.views.casualties.urls', namespace='casualties')),
    path(r'static/<path:path>', serve, {
        'document_root': STATIC_ROOT
        }),
    path(r'catfood', sitefeeds.CatFood(), name='catfood'),
    path(r'login', auth_views.LoginView.as_view(template_name='user/login.html',
                                                authentication_form=siteforms.UserLogin),
         name='user.login'),
    path(r'logout', auth_views.LogoutView.as_view(), name='user.logout'),
    path('admin/tools/', djangoadmin.site.urls, name='admin.tools'),
    path('set/', include('app.views.set.urls', namespace='set'))
    ]

app/views/home.py
from django.shortcuts import render
from django.urls import path
from django.views import View

from app.utils.db import conn


class HomeView(View):
    url_pattern = ''
    name = 'index'

    def get(self, request):
        return render(request, 'main.html', {
            'img': conn.latest_cat
            })

app_name = 'home'
urlpatterns = [path('', HomeView.as_view(), name='index')]

app/templates/fragments/media.html
{% if src.filetype == "img" %}
    <img alt="this is probably a picture of the cat's bum" src="{{ src.url }}" class="{{ classes }} media-item"
         {% if id is not None %}id="{{ id }}"{% endif %}
    {% if event is not None and method is not None %}{{ event }}="{{ method }}(
        {% if pk is not None %}{{ pk }}{% endif %})"{% endif %}/>
{% elif src.filetype == "video" %}
    <video autoplay muted width="{{ max_width|default:640 }}" height="{{ max_width|default:640 }} * (480/640)"
           class="{{ classes }} media-item"
           {% if id is not None %}id="{{ id }}"{% endif %} autoplay
           loop {% if event is not None and method is not None %}{{ event }}="{{ method }}(
        {% if pk is not None %}{{ pk }}{% endif %})"{% endif %}>
        <source src="{{ src.url }}" type="video/mp4">
        this is a video, and apparently your browser doesn't support that.
    </video>
{% endif %}

app/templates/fragments/navbar.html
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse" style="border: hidden;" aria-expanded="false">
        <i class="fa fa-bars"></i>
      </button>
      <a class="navbar-brand" href="/">Is the cat in?</a>
    </div>
    <div class="collapse navbar-collapse" id="navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
          {% if request.user.is_superuser %}
              <li><a class="icon-admin" href="{% url 'catmin:index' %}">Admin</a></li>
          {% endif %}
        <li><a class="icon-home" href="{% url 'home:index' %}">Home</a></li>
        <li><a class="icon-history" href="{% url 'history:index' '1' %}">History</a></li>
        <li><a class="icon-highlights" href="{% url 'highlights:index' '1' %}">Highlights</a></li>
        <li><a class="icon-rip" href="{% url 'casualties:index' %}">R.I.P.</a></li>
        <li><a class="icon-feed" href="{% url 'catfood' %}" target="_blank">Feed</a></li>
        <li><a class="icon-github" href="https://github.com/alycejenni/isthecatin" target="_blank">Github</a></li>
      </ul>
    </div>
  </div>
</nav>

app/templates/fragments/scripts.html
{% load static %}
<!-- Google Tag Manager -->
<script>(function (w, d, s, l, i) {
    w[l] = w[l] || [];
    w[l].push({
        'gtm.start': new Date().getTime(), event: 'gtm.js'
    });
    var f = d.getElementsByTagName(s)[0],
        j = d.createElement(s), dl = l != 'dataLayer' ? '&l=' + l : '';
    j.async = true;
    j.src =
        'https://www.googletagmanager.com/gtm.js?id=' + i + dl;
    f.parentNode.insertBefore(j, f);
})(window, document, 'script', 'dataLayer', 'GTM-WRZFQ6B');</script>
<!-- End Google Tag Manager -->
<script src="https://code.jquery.com/jquery-3.1.1.min.js"
        integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="
        crossorigin="anonymous"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="{% static 'javascript/popups.js' %}"></script>

app/templates/fragments/styles.html
{% load static %}
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat:300,500,700|Lato">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="{% static 'css/styles.css' %}" >
<link rel="shortcut icon" href="{% static 'images/favicon.png' %}">
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">