app/views/highlights/urls.py
from django.urls import path

from . import views

view_classes = [views.IndexView, views.CreateView]

app_name = 'highlights'
urlpatterns = [path(v.url_pattern, v.as_view(), name=v.name) for v in view_classes]

app/views/history/urls.py
from django.urls import path

from . import views

view_classes = [views.IndexView]

app_name = 'history'
urlpatterns = [path(v.url_pattern, v.as_view(), name=v.name) for v in view_classes]

config/urls.py
from django.contrib import admin as djangoadmin
from django.contrib.auth import views as auth_views
from django.urls import include, path
from django.views.static import serve

from app.obj import forms as siteforms
from app.pages import feeds as sitefeeds
from .settings.base import STATIC_ROOT

urlpatterns = [
    path('', include('app.views.home', namespace='home')),
    path('admin/', include('app.views.admin.urls', namespace='catmin')),
    path('history/', include('app.views.history.urls', namespace='history')),
    path('highlights/', include('app.views.highlights.urls', namespace='highlights')),
    path('casualties/', include('app.views.casualties.urls', namespace='casualties')),
    path(r'static/<path:path>', serve, {
        'document_root': STATIC_ROOT
        }),
    path(r'catfood', sitefeeds.CatFood(), name='catfood'),
    path(r'login', auth_views.LoginView.as_view(template_name='user/login.html',
                                                authentication_form=siteforms.UserLogin),
         name='user.login'),
    path(r'logout', auth_views.LogoutView.as_view(), name='user.logout'),
    path('admin/tools/', djangoadmin.site.urls, name='admin.tools'),
    path('set/', include('app.views.set.urls', namespace='set'))
    ]

catflapsite/forms.py
from django import forms
from .models import Casualty, Highlight
from django.contrib.auth.forms import AuthenticationForm


class UserLogin(AuthenticationForm):
    username = forms.CharField(label="username", max_length=30, widget=forms.TextInput(attrs={
        "tabindex": 1
    }))
    password = forms.CharField(label="password", widget=forms.PasswordInput(attrs={
        "tabindex": 2
    }))


class NominateHighlight(forms.ModelForm):
    url = forms.URLField(required=True, widget=forms.HiddenInput(attrs={
        "class": "hidden-url"
    }))
    comment = forms.CharField(required=False, widget=forms.TextInput(attrs={
        "style": "width:100%"
    }))

    class Meta:
        model = Highlight
        fields = ["url", "comment"]


class CreateCasualty(forms.ModelForm):
    url = forms.CharField(required=False, widget=forms.TextInput(attrs={
        "onkeyup": "refreshCaught()",
        "onchange": "refreshCaught()",
        "placeholder": "image url here",
        "class": "form-control"
    }))
    creature_type = forms.CharField(widget=forms.TextInput(attrs={
        "class": "form-control"
    }))
    creature_name = forms.CharField(required=False, widget=forms.TextInput(attrs={
        "class": "form-control"
    }))
    doa = forms.BooleanField(required=False, widget=forms.CheckboxInput(attrs={
        "class": "toggle-cat",
        "onchange": "checkDOA()"
    }))
    known_deceased = forms.BooleanField(required=False, widget=forms.CheckboxInput(attrs={
        "class": "toggle-cat"
    }))
    additional_image = forms.CharField(required=False, widget=forms.TextInput(attrs={
        "onkeyup": "refreshAdditional()",
        "onchange": "refreshAdditional()",
        "placeholder": "image url here",
        "class": "form-control"
    }))
    guilty_cat = forms.CharField(required=False, widget=forms.TextInput(attrs={
        "onkeyup": "refreshGuilty()",
        "onchange": "refreshGuilty()",
        "placeholder": "image url here",
        "class": "form-control"
    }))
    time_taken = forms.DateField(required=False, widget=forms.DateInput(attrs={
        "class": "form-control",
        "type": "date"
    }))

    class Meta:
        model = Casualty
        fields = ["url", "creature_type", "creature_name", "doa", "known_deceased", "additional_image", "guilty_cat",
                  "time_taken"]

app/views/highlights.py
from django.shortcuts import redirect, render
from django.views import View

from app.obj.forms import CreateHighlight
from app.obj.models import Highlight
from app.utils import db

prefix = r'^highlights'


class HighlightsView(View):
    url_pattern = prefix + r'/(?P<page>[0-9]+)$'
    name = 'highlights.index'

    def get(self, request, page):
        page = int(page)
        page_size_limit = 20
        page_start = (page - 1) * page_size_limit
        page_end = page * page_size_limit
        imgs = db.get_cats_from_objects(Highlight.objects, page_start, page_end, ['comment'])
        return render(request, 'highlights.html', {
            'imgs': imgs,
            'page': page,
            'more_pages': (len(imgs) != 0) and (page_end < len(imgs) - 1)
            })

    def post(self, request, page):
        page = int(page)
        btn = request.POST['btn_submit']
        if btn == 'Next page':
            return redirect(self.name, page=str(page + 1))
        elif btn == 'Previous page':
            return redirect(self.name, page=str(page - 1))
        else:
            self.get(request, page)


class HighlightsCreateView(View):
    url_pattern = prefix + r'/create$'
    name = 'highlights.create'

    def post(self, request):
        form = CreateHighlight(request.POST)
        if form.is_valid():
            form.save()
            print('saved')
        return redirect(HighlightsView.name, page='1')

app/views/highlights/views.py
from django.shortcuts import redirect, render
from django.views import View

from app.obj.forms import CreateHighlight
from app.obj.models import Highlight
from app.utils.db import conn


class IndexView(View):
    url_pattern = '<int:page>'
    name = 'index'

    def get(self, request, page):
        page = int(page)
        page_size_limit = 20
        page_start = (page - 1) * page_size_limit
        page_end = page * page_size_limit
        imgs = conn.get_cats_from_objects(Highlight.objects, page_start, page_end, ['comment'])
        return render(request, 'highlights.html', {
            'imgs': imgs,
            'page': page,
            'more_pages': len(conn.get_cats_from_objects(Highlight.objects, page_end, page_end+1, ['comment'])) != 0
            })

    def post(self, request, page):
        page = int(page)
        btn = request.POST['btn_submit']
        if btn == 'Next page':
            return redirect('highlights:index', page=page + 1)
        elif btn == 'Previous page':
            return redirect('highlights:index', page=page - 1)
        else:
            self.get(request, page)


class CreateView(View):
    url_pattern = 'create'
    name = 'create'

    def post(self, request):
        form = CreateHighlight(request.POST)
        if form.is_valid():
            form.save()
            print('saved')
        return redirect('highlights:index', page='1')

app/views/history.py
from django.shortcuts import redirect, render
from django.views import View

from app.obj.forms import CreateHighlight


class HistoryView(View):
    url_pattern = r'^history/(?P<page>[0-9]+)$'
    name = 'history.index'

    def get(self, request, page):
        page = int(page)
        page_size_limit = 18
        page_start = (page - 1) * page_size_limit
        page_end = page * page_size_limit
        is_mod = request.user.groups.filter(name__in=['Moderators', 'Admin']).exists()
        return render(request, 'history.html', {
            'imgs': kitty.cats(page_start, page_size_limit),
            'nomination_form': CreateHighlight(),
            'page': page,
            'more_pages': len(kitty.cats(page_end, 1)) != 0,
            'is_mod': is_mod or request.user.is_superuser
            })

    def post(self, request, page):
        page = int(page)
        btn = request.POST['btn_submit']
        if btn == 'Next page':
            return redirect(self.name, page=str(page + 1))
        elif btn == 'Previous page':
            return redirect(self.name, page=str(page - 1))
        else:
            self.get(request, page)

app/views/history/views.py
from django.shortcuts import redirect, render
from django.views import View

from app.obj.forms import CreateHighlight
from app.utils.db import conn


class IndexView(View):
    url_pattern = '<int:page>'
    name = 'index'

    def get(self, request, page):
        page = int(page)
        page_size_limit = 18
        page_start = (page - 1) * page_size_limit
        page_end = page * page_size_limit
        is_mod = request.user.groups.filter(name__in=['Moderators', 'Admin']).exists()
        return render(request, 'history.html', {
            'imgs': conn.cats(page_start, page_size_limit),
            'nomination_form': CreateHighlight(),
            'page': page,
            'more_pages': len(conn.cats(page_end, 1)) != 0,
            'is_mod': is_mod or request.user.is_superuser
            })

    def post(self, request, page):
        page = int(page)
        btn = request.POST['btn_submit']
        if btn == 'Next page':
            return redirect('history:index', page=page + 1)
        elif btn == 'Previous page':
            return redirect('history:index', page=page - 1)
        else:
            self.get(request, page)

app/views/set/views.py
from django.shortcuts import redirect
from django.views import View

from app.utils import kitty


class SetNotCat(View):
    url_pattern = 'notcat'
    name = 'notcat'

    def post(self, request):
        img = request.POST.get('img', None)
        page = request.POST.get('page', 1)
        if img is not None:
            try:
                kitty.set_not_cat(img)
            except Exception as e:
                print(e)
        return redirect('history:index', page=page)

app/templates/basepage.html
{% load cattags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% include 'fragments/scripts.html' %}
    {% include 'fragments/styles.html' %}
    {% block scripts %}{% endblock %}
</head>
<body>
<noscript>
    <iframe src="https://www.googletagmanager.com/ns.html?id=GTM-WRZFQ6B"
            height="0" width="0" style="display:none;visibility:hidden"></iframe>
</noscript>
{% include 'fragments/navbar.html' %}
{% block content %}
{% endblock %}
<div style="position: fixed; bottom: 0; left: 0;">
<small class="icon-tiny">
{% if request.user.is_authenticated %}
    <a href="{% url 'user.logout' %}"><i class="fa fa-unlock" aria-hidden="true"></i></a> ({{ request.user }})
{% else %}
    <a href="{% url 'user.login' %}"><i class="fa fa-lock" aria-hidden="true"></i></a>
{% endif %}
{% last_committed %}
</small>
</div>
</body>
</html>

app/templates/createcasualty.html
{% extends "basepage.html" %}
{% load static %}
{% block title %}
    what has the cat dragged in now?
{% endblock %}
{% block scripts %}
    <script src="{% static "javascript/createcasualty.js" %}" type="text/javascript"></script>
{% endblock %}
{% block content %}
    <form method="post" action="{% url 'casualties:create' %}">
        {% csrf_token %}
        <div class="container">
            <div class="row padded-row">
                <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4 question">
                    Caught in the act!
                </div>
                <div class="col-xs-8 col-sm-8 col-md-8 col-lg-8 answer">
                    {{ form.url }}
                </div>
            </div>
            <div class="row padded-row">
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                    {% include 'fragments/media.html' with src=img classes="img-rounded img-responsive center-block minisize" id="id_caughtintheact" %}
                </div>
            </div>
            <div class="row padded-row">
                <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4 question">
                    What is it?
                </div>
                <div class="col-xs-8 col-sm-8 col-md-8 col-lg-8 answer">
                    {{ form.creature_type }}
                </div>
            </div>
            <div class="row padded-row">
                <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4 question">
                    What did we call it?
                </div>
                <div class="col-xs-8 col-sm-8 col-md-8 col-lg-8 answer">
                    {{ form.creature_name }}
                </div>
            </div>
            <div class="row padded-row">
                <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6 question">
                    <table class="question">
                        <tr>
                            <td style="padding-right: 10px;">Was it dead on arrival?</td>
                            <td>
                                <div>
                                    {{ form.doa }}
                                    <label for="id_doa">
                                    </label>
                                </div>
                            </td>
                        </tr>
                    </table>
                </div>
                <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6 answer">
                    <div id="known_deceased" style="visibility: hidden">
                        <table class="answer">
                            <tr>
                                <td style="padding-right: 10px;">Is it dead now?</td>
                                <td><div>
                                    {{ form.known_deceased }}
                                    <label for="id_known_deceased" id="lblKD">
                                    </label>
                                </div></td>
                            </tr>
                        </table>
                    </div>
                </div>
            </div>
            <div class="row padded-row">
                <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4 question">
                    Fancy adding a picture of the casualty?
                </div>
                <div class="col-xs-8 col-sm-8 col-md-8 col-lg-8 answer">
                    {{ form.additional_image }}
                </div>
            </div>
            <div class="row padded-row">
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                    <img src="" id="id_additional" class="img-rounded img-responsive center-block"
                         alt="poor critter"
                         title="poor critter" style="max-width: 300px;">
                </div>
            </div>
            <div class="row padded-row">
                <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4 question">
                    What about a picture of the guilty party?
                </div>
                <div class="col-xs-8 col-sm-8 col-md-8 col-lg-8 answer">
                    {{ form.guilty_cat }}
                </div>
            </div>
            <div class="row padded-row">
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                    <img src="" id="id_guilty" class="img-rounded img-responsive center-block"
                         alt="a picture of the cat not looking in the least bit guilty"
                         title="naughty pussycat" style="max-width: 300px;">
                </div>
            </div>
            <div class="row padded-row">
                <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4 question">
                    When was this?
                </div>
                <div class="col-xs-8 col-sm-8 col-md-8 col-lg-8 answer">
                    {{ form.time_taken }}
                </div>
            </div>
            <div class="row center-block">
                <hr>
                <input align="center" class="btn btn-primary center-block" type="submit" value="submit"/>
                <hr>
            </div>
        </div>
    </form>
{% endblock %}

app/templates/highlights.html
{% extends "basepage.html" %}
{% load static %}
{% load l10n %}
{% block title %}
    hall of infamy
{% endblock %}
{% block content %}
    <div class="container">
        <div class="row padded-row">
            {% for img in imgs %}
                <div class="col-md-4 col-xs-8">
                    <a href="#" class="zoomthumb">
                        <div style="position: relative; top: -20px; z-index: -100;">
                            {% include "fragments/media.html" with src=img.media classes="img-thumbnail" %}</div>
                    </a>
                    <p style="position: relative; top: -20px; text-align: center;">{{ img.media.time_taken|localize }}</p>
                </div>
                <div class="col-md-2 col-xs-4">
                    {% for comment in img.comment %}
                        <p>- {{ comment }}</p>
                    {% endfor %}
                </div>
            {% endfor %}
        </div>
    </div>
    <form method="post" action="{% url 'highlights:index' page %}"> {% csrf_token %}
        <div class="row padded-row">
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 text-center">
                {% if page > 1 %}
                    <input type="submit" name="btn_submit" value="Previous page" class="btn btn-primary">
                {% endif %}
                {% if more_pages %}
                    <input type="submit" name="btn_submit" value="Next page" class="btn btn-primary">
                {% endif %}
            </div>
        </div>
    </form>
    <div id="zoomcat" style="width: 100%; margin: 0 0 0 0;">
        <div id="zoomcat-body" style="width: 100%" align="center">
        </div>
    </div>
    <script>
        loadZoom();
    </script>
{% endblock %}

app/templates/history.html
{% extends "basepage.html" %}
{% load static %}
{% load l10n %}
{% block title %}
    was the cat in?
{% endblock %}
{% block content %}
    <div class="container">
        <div class="row padded-row">
            {% for img in imgs %}
                <div class="col-md-4 col-xs-6 img-box">
                    <div style="text-align: right;">
                        {% if is_mod %}
                            <table>
                                <tr>
                                    <td>
                                        <form method="post" action="{% url 'set:notcat' %}">{% csrf_token %}
                                            <input type="hidden" value="{{ img.id.decode }}" name="img">
                                            <input type="hidden" value="{{ page }}" name="page">
                                            <input type="image" src="{% static 'images/notcat.png' %}" width="20px"
                                                   alt="button to mark as not a cat"
                                                   title="this isn't a cat!"/></form>
                                    </td>
                                    <td>
                                        <form method="post" action="{% url 'casualties:create' %}">{% csrf_token %}
                                            <input type="hidden" value="{{ img.id }}" name="img">
                                            <input type="image" src="{% static 'images/skull-icon.png' %}" width="20px"
                                                   alt="button to mark image as containing possible casualty"
                                                   title="he's got something!"/></form>
                                    </td>
                                    <td>
                                        <img href="#" class="addhighlight" src="{% static 'images/star.png' %}"
                                             width="20px" style="padding:0; margin:0; top:-3px; position: relative;"
                                             alt="button to mark image as a really good one"
                                             title="nominate for the hall of infamy!"/>
                                    </td>
                                </tr>
                            </table>
                        {% else %}
                            <div><img href="#" class="addhighlight" src="{% static 'images/star.png' %}"
                                      width="20px" style="padding:0; margin:0; top:-3px; position: relative;"
                                      alt="button to mark image as a really good one"
                                      title="nominate for the hall of infamy!"/></div>
                        {% endif %}
                    </div>
                    <a href="#" class="zoomthumb">
                        <div style="position: relative; top: -20px; z-index: -100;">
                            {% include "fragments/media.html" with src=img classes="img-thumbnail" %}</div>
                    </a>
                    <p style="position: relative; top: -20px; text-align: center;">{{ img.time_taken|localize }}</p>
                </div>
            {% endfor %}
        </div>
        <form method="post" action="{% url 'history:index' page %}"> {% csrf_token %}
            <div class="row padded-row">
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 text-center">
                    {% if page > 1 %}
                        <input type="submit" name="btn_submit" value="Previous page" class="btn btn-primary">
                    {% endif %}
                    {% if more_pages %}
                        <input type="submit" name="btn_submit" value="Next page" class="btn btn-primary">
                    {% endif %}
                </div>
            </div>
        </form>
    </div>
    <div id="zoomcat" style="width: 100%; margin: 0;" class="popup">
        <div id="zoomcat-body" style="width: 100%" align="center">
        </div>
    </div>
    <div id="popupHighlight" style="width: 100%; margin: 0;" class="popup">
        <form method="post" action="{% url 'highlights:create' %}">
            {% csrf_token %}
            <div class="container-fluid">
                <div class="row">
                    <div class="col-xs-7 col-sm-7 col-md-7 col-lg-7" id="popupHighlight-media">
                    </div>
                    <div class="col-xs-5 col-sm-5 col-md-5 col-lg-5">
                        <div class="row">
                            <label for="popupHighlight-comment">Tell me why this is so good:</label>
                        </div>
                        <div class="row padded-row">
                            {{ nomination_form.comment }}
                            {{ nomination_form.url }}
                        </div>
                        <div class="row">
                            (you can nominate something for the hall of infamy more than once if you've got a lot to
                            say!)
                        </div>
                        <input align="center" class="btn btn-primary center-block" type="submit" value="submit"/>
                    </div>
                </div>
            </div>
        </form>
    </div>
    <script>
        loadZoom();
        loadNominate();
    </script>
{% endblock %}

app/templates/main.html
{% extends "basepage.html" %}
{% block title %}
    is the cat in?
{% endblock %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-md-offset-3">
                {% include "fragments/media.html" with src=img classes="img-responsive cat-img" %}
            </div>
            <div class="col-md-3">
                <h3 class="img-metadata">Latest photo <i class="fa fa-camera"></i></h3>
                <p class="img-metadata">Taken {{ img.time_ago_str }} ago.</p>
            </div>
        </div>
        <div class="text-center">
        {% if img.direction == 0 %}
            {#if the cat is out#}
            <h1 class="in-out-msg">Looks like he's out <i class="fa fa-exclamation-triangle"></i></h1>
            <h2 class="in-out-msg">Decimating the local rabbit population</h2>
        {% elif img.direction == 1 %}
            <h1 class="in-out-msg">Looks like he's in <i class="fa fa-check"></i></h1>
            <h2 class="in-out-msg">Grabbing some Zs</h2>
        {% else %}
            {#if he's being a quantum boy#}
            <h1 class="in-out-msg">We're not sure where he is <i class="fa fa-bathtub"></i></h1>
            <h2 class="in-out-msg">Aw, darn</h2>
        {% endif %}
        </div>
    </div>
{% endblock %}

app/templates/rip.html
{% extends "basepage.html" %}
{% load static %}
{% block title %}
    what has the cat dragged in?
{% endblock %}
{% block scripts %}
    <script src="{% static "javascript/rip.js" %}" type="text/javascript"></script>
{% endblock %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-12 col-xs-12 carousel">
                {% for animal in animals %}
                    <div class="carousel-cell">
                        {% if animal.known_deceased %}
                            {% include "fragments/media.html" with src=animal.media classes="img-thumbnail ded" event="onclick" method="displayCasualty" pk=animal.pk %}
                        {% else %}
                            {% include "fragments/media.html" with src=animal.media classes="img-thumbnail notded" event="onclick" method="displayCasualty" pk=animal.pk %}
                        {% endif %}
                    </div>
                {% endfor %}
            </div>
        </div>
        <hr>
        <div class="row padded-row">
            <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
                <span class="h1" id="obit_header"></span>
                <p id="obit_desc"></p>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8">
                <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6" id="catflappicture"></div>
                <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6" id="critterpicture"></div>
                <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6" id="guiltycat"></div>
            </div>
        </div>
    </div>
{% endblock %}